version: '3'
services:
  engine-lab:
    container_name: engine.lab
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.centos8
    volumes:
      - ..:/usr/local/engine
      - ../examples:/usr/local/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/usr/local/engine:${PYTHONPATH}
    command:
      - /bin/bash
      - -c 
      - |
        ./install.sh -p /usr/local/nginx
        mkdir -p /usr/local/nginx/logs
        touch /usr/local/nginx/logs/debug.log
        tail -f /dev/null
