version: '3'
services:

  engine_compiler:
    container_name: engine.compiler
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.centos8
      args:
        - nginx_version=1.19.3
    volumes:
      - ~/code/engine:/var/engine
    ports:
      - "8080:80"
    environment:
      - C_INCLUDE_PATH=/usr/include/python3.6m
    command:
      - /bin/bash
      - -c 
      - |
        ./configure --with-debug \
          --prefix=/usr/local/nginx \
          --add-module=/var/engine/engine \
          --with-ld-opt="`python3.6-config --ldflags`"
        make
        make install
        tail -f /dev/null
