version: '3'
services:
  engine-common: &engine-common
    build:
      context: ../../engine
      dockerfile: ./docker/Dockerfile.centos8
    ports:
      - "8080:8080"

  engine-examples:
    <<: *engine-common
    container_name: engine.examples
    volumes:
      - ..:/usr/local/engine
      - ../examples:/usr/local/app
    environment:
      - PYTHONPATH=/usr/local/engine:${PYTHONPATH}
    command:
      - /bin/bash
      - -c 
      - |
        ./install.sh -p /usr/local/nginx
        mkdir -p /usr/local/nginx/logs
        touch /usr/local/nginx/logs/debug.log
        /usr/local/nginx/sbin/nginx -g "daemon off;" -c /usr/local/app/ngx_conf/nginx.conf
